name: Terraform Deployment Pipeline

on:
  push:
    branches:
      - main     # Trigger the pipeline when changes are pushed to the main branch
  pull_request:
    branches:
      - main     # Trigger on PR to the main branch as well

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.7   # Specify your desired Terraform version

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan

    - name: Output Terraform Apply result
      run: echo "Terraform apply completed successfully"
