name: Terraform Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.7

    - name: Decode GCP Credentials Secret
      run: |
        # Decode the base64 encoded GCP credentials secret and save it as a JSON file
        echo "${{ secrets.GCP_CREDENTIALS }}" | base64 --decode > /tmp/gcp_credentials.json
        # Optionally, print the decoded JSON (be cautious with sensitive info)
        echo "GCP credentials decoded successfully"
      shell: bash

    - name: Verify GCP Credentials File
      run: |
        # Check if the credentials file exists and is not empty
        if [ ! -s /tmp/gcp_credentials.json ]; then
          echo "GCP credentials file is empty or does not exist"
          exit 1
        else
          echo "GCP credentials file created successfully"
        fi
      shell: bash

    - name: Debug Environment
      run: env | sort

    - name: Validate GCP Credentials File Format
      run: |
        # Validate the JSON format (this will help catch any errors)
        cat /tmp/gcp_credentials.json | jq .
      shell: bash

    - name: Terraform Init
      run: terraform init
      working-directory: ./src/main/terraform

    - name: Terraform Plan
      env:
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp_credentials.json  # Point to the credentials file
      run: terraform plan
      working-directory: ./src/main/terraform

    - name: Import Cloud SQL Instance into Terraform State
      run: |
        terraform import google_sql_database_instance.my_mysql_instance projects/awesome-destiny-436710-j1/instances/cloud-sql
        terraform import google_sql_database.my_database projects/awesome-destiny-436710-j1/instances/cloud-sql/databases/terraform_database
        terraform import google_sql_user.my_mysql_user projects/awesome-destiny-436710-j1/instances/cloud-sql/users/%/cloud
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp_credentials.json  # Point to the credentials file
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      working-directory: ./src/main/terraform

    - name: Terraform Apply
      env:
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp_credentials.json  # Point to the credentials file
      run: terraform apply -auto-approve -var="db_password=${{ secrets.DB_PASSWORD }}"
      working-directory: ./src/main/terraform
