name: Terraform Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.7

    - name: Setup GCP Credentials
      run: printf '%s' "${{ secrets.GOOGLE_CREDENTIALS }}" > /tmp/credentials.json
      shell: bash

    - name: Validate JSON File Exists and Is Non-Empty
      run: |
        if [ ! -s /tmp/credentials.json ]; then
          echo "Credentials file is empty or does not exist"
          exit 1
        fi
        cat /tmp/credentials.json
      shell: bash

    - name: Validate JSON Format
      run: cat /tmp/credentials.json | jq .
      shell: bash

    - name: Terraform Init
      run: terraform init
      working-directory: ./src/main/terraform

    - name: Terraform Plan
      env:
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        GOOGLE_CREDENTIALS: /tmp/credentials.json  # Point to the credentials file
      run: terraform plan
      working-directory: ./src/main/terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./src/main/terraform
