name: Terraform Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.7

    - name: Decode GCP Credentials Secret
      run: |
        echo "${{ secrets.GCP_CREDENTIALS }}" | base64 --decode > /tmp/gcp_credentials.json
        echo "GCP credentials decoded successfully"
      shell: bash

    - name: Verify GCP Credentials File
      run: |
        if [ ! -s /tmp/gcp_credentials.json ]; then
          echo "GCP credentials file is empty or does not exist"
          exit 1
        else
          echo "GCP credentials file created successfully"
      shell: bash

    - name: Initialize Terraform
      run: terraform init
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp_credentials.json

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp_credentials.json
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

    - name: Terraform Apply
      if: github.event_name == 'push'
      run: terraform apply -auto-approve tfplan
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp_credentials.json
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
