name: Terraform Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.7

    - name: Set up GCP credentials
      run: echo "${{ secrets.GCP_CREDENTIALS }}" > /tmp/credentials.json
      # Write the GCP credentials from GitHub Secrets to a temporary file.

    - name: Terraform Init
      run: terraform init
      working-directory: ./src/main/terraform

    - name: Terraform Plan
      env:
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        GOOGLE_CREDENTIALS: /tmp/credentials.json  # Point to the credentials file
      run: terraform plan
      working-directory: ./src/main/terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./src/main/terraform
